### ISSUE TITLE
While mass url adding in raw_urls tools not working 

### ISSUE THREAD

**Issue by noob0x01** [devanshbatham/Drishti#1]
██▄   █▄▄▄▄ ▄█    ▄▄▄▄▄    ▄  █    ▄▄▄▄▀ ▄█ 
            █  █  █  ▄▀ ██   █     ▀▄ █   █ ▀▀▀ █    ██ 
            █   █ █▀▀▌  ██ ▄  ▀▀▀▀▄   ██▀▀█     █    ██ 
            █  █  █  █  ▐█  ▀▄▄▄▄▀    █   █    █     ▐█ 
            ███▀    █    ▐               █    ▀       ▐ 
                   ▀                    ▀               
                         -coded with <3 by Devansh Batham

    
 [~] Loading URLs
 [~] Sending Requests

Traceback (most recent call last):
  File "drishti.py", line 126, in <module>
    main()
  File "drishti.py", line 17, in main
    asyncio.run(download_url_contents())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "drishti.py", line 30, in download_url_contents
    await gen_url_tasks(session, 'raw_urls.txt')
  File "drishti.py", line 91, in gen_url_tasks
    results = await asyncio.gather(*tasks)
  File "drishti.py", line 34, in fetch_url
    async with session.get(url) as response:
  File "/root/py37-venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/root/py37-venv/lib/python3.7/site-packages/aiohttp/client.py", line 473, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/root/py37-venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "/root/py37-venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: https://

**Comment by devanshbatham** [comment]
make sure the urls entered in the file must be in the right format , (no extra new line , no extra space)

**Comment by devanshbatham** [comment]
Can send me the URL file , if possible ? Over my email ? devanshbatham009@gmail.com

**Comment by noob0x01** [comment]
Fixed . Thanks .
