### ISSUE TITLE
Drishti with Large Subdomain List

### ISSUE THREAD

**Issue by rohitcoder** [devanshbatham/Drishti#5]
Hello @devanshbatham  😁

Bhaai, Apun try kar rha tha Yahoo.com k subdomain list ko Drishti k saath use krne ka Total 16,130 Subdomains fetch hue using ``findomain -t yahoo.com``

But after running drishti for few minutes, i got this error

```python
Task exception was never retrieved
future: <Task finished name='Task-33655' coro=<TCPConnector._resolve_host() done, defined at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py:774> exception=gaierror(8, 'nodename nor servname provided, or not known')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(Task exception was never retrieved
future: <Task finished name='Task-33655' coro=<TCPConnector._resolve_host() done, defined at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py:774> exception=gaierror(8, 'nodename nor servname provided, or not known')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(...................................
```

At the end of execution its showing

```
    [+] URLs Checked  : 32260
    [!] Total execution time    : 311.86s
```

Why it's showing 32260 URL's if i am having 16,130 URLS is it checking both 80 and 443 ports or something else?

![Screenshot 2020-07-04 at 12 02 11 AM](https://user-images.githubusercontent.com/17665703/86491854-9e2add80-bd89-11ea-92d6-3fa0e7b38588.png)

Any alternative instead of splitting this in multiple parts? I think this happened because of timeouts or request return nothing?

**Comment by rohitcoder** [comment]
Solved from Private chat with @devanshbatham  😄
